/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachinecontrolsystem.ui;

import javax.swing.JLabel;
import javax.swing.JTextField;

import vendingmachinecontrolsystem.model.Coin;
import vendingmachinecontrolsystem.model.Drink;

/**
 *
 * @author Dannel
 */
public class MachineryPanel extends javax.swing.JFrame {

	private boolean isLocked = true;

	/**
	 * Creates new form MachineryPanel
	 */
	public MachineryPanel() {
		initComponents();
		jCheckBox1.setSelected(isLocked);
	}

	public void addNewCoins(Coin coin) {
		if (!coin.getName().equalsIgnoreCase("Invalid")) {
			JLabel jLabel = new JLabel();
			jLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
			jLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
			jLabel.setText(coin.getName());

			JTextField jTextField = new JTextField();
			jTextField.setBackground(new java.awt.Color(0, 0, 0));
			jTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
			jTextField.setForeground(java.awt.Color.YELLOW);
			jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
			jTextField.setText(String.valueOf(coin.getQuantity()));

			coinPanel.add(jLabel);
			coinPanel.add(jTextField);
		}
	}

	public void addNewDrink(Drink drink) {
		JLabel jLabel = new JLabel();
		jLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel.setText(drink.getName().replace("_", " ").toUpperCase());

		JTextField jTextField = new JTextField();
		jTextField.setBackground(new java.awt.Color(0, 0, 0));
		jTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jTextField.setForeground(java.awt.Color.YELLOW);
		jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField.setText(String.valueOf(drink.getQuantity()));

		drinkPanel.add(jLabel);
		drinkPanel.add(jTextField);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		coinPanel = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		drinkPanel = new javax.swing.JPanel();
		jCheckBox1 = new javax.swing.JCheckBox();

		setTitle("VMCS - Machinery Panel");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Machinery Panel");

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel4.setText("Quantity of Coins Available:");

		coinPanel.setLayout(new java.awt.GridLayout(0, 2));

		jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel7.setText("Quantity of Drinks Available:");

		drinkPanel.setLayout(new java.awt.GridLayout(0, 2));

		jCheckBox1.setText("Door Locked");
		jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox1ItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
						.addComponent(coinPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(drinkPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel4).addComponent(jLabel7))
								.addGap(0, 0, Short.MAX_VALUE))
						.addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jLabel4).addGap(18, 18, 18)
						.addComponent(coinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
						.addGap(18, 18, 18).addComponent(jLabel7).addGap(18, 18, 18)
						.addComponent(drinkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
						.addGap(18, 18, 18).addComponent(jCheckBox1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jCheckBox1ItemStateChanged
		// TODO add your handling code here:
		isLocked = !isLocked;
		System.out.println("isLocked: " + isLocked);
	}// GEN-LAST:event_jCheckBox1ItemStateChanged

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel coinPanel;
	private javax.swing.JPanel drinkPanel;
	// End of variables declaration//GEN-END:variables
}
